on:
  push:
    branches:
      - main

jobs:
  verify-alpine-3_14:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/container-scan@v0
        with:
          image-name: alpine:3.14
  verify-alpine-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/container-scan@v0
        with:
          image-name: alpine:latest
  verify-debian-11-slim:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/container-scan@v0
        with:
          image-name: debian:11-slim
  verify-debian-bookworm-slim:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/container-scan@v0
        with:
          image-name: debian:bookworm-slim
