on:
  push:
    branches:
      - main

jobs:
  verify-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker build . -t experimental:verify
      - uses: Azure/container-scan@v0
        with:
          image-name: groundhog2k/experimental:verify